### ISSUE TITLE
Gcts integration from Jenkins

### ISSUE THREAD

**Issue by roshvin** [SAP-samples/abap-platform-ci-cd-samples#9]
Hi,
we are using on Prem SAP system and its integrated to GCTS , we are looking to run deployment from jenkins. could you pls suggest which way to go forward from your example here. 
i am getting confusion on how to connect the Gcts system from jenkins.

**Comment by DanielMieg** [comment]
Hi,

the examples in this repository refer to the product SAP BTP, ABAP Environment. The pipeline used in this repository only works for this type of ABAP system.

For the on Premise use case, there are several steps that can be used to create a self-made pipeline. The documentation, e.g. for the "Clone Repositories" step, can be found here: https://www.project-piper.io/steps/gctsCloneRepository/
